site_name: My Docs
docs_dir: pages
site_dir: site

exclude_docs: |
  generated-api/

theme:
  name: material

plugins:
  - search
  - mkdoxy:
      save-api: pages/generated-api
      projects:
        onboardFirmware:
          src-dirs: ../onboard/firmware/src
          full-doc: true
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h*"
            RECURSIVE: true

nav:
  - Home: index.md
  - Source files: onboardFirmware/files.md
  - Functions: onboardFirmware/example_8cpp.md
